dispositivo/urls.py
# estructura/urls.py
from django.urls import path

from .views import SensorListado, SensorCrear, SensorActualizar, SensorDetalle, SensorEliminar, \
    ActuadorListado, ActuadorCrear, ActuadorActualizar, ActuadorDetalle, ActuadorEliminar, \
        DispositivoListado, DispositivoCrear, DispositivoActualizar, DispositivoDetalle, DispositivoEliminar, \
            TipoSensorListado, TipoSensorCrear, TipoSensorActualizar, TipoSensorDetalle, TipoSensorEliminar, \
                TipoActuadorListado, TipoActuadorCrear, TipoActuadorActualizar, TipoActuadorDetalle, TipoActuadorEliminar, \
                    ajax_controlador_detalle, ajax_controlador_actualizar, SensorPubListado, ajax_sensor_pubs, ajax_sensor_plot, \
                        ajax_controller_plot, ajax_status_pubs
from dispositivo.views import SensorMonitor, SensorMonitor2

urlpatterns = [
    path('controlador/', DispositivoListado.as_view(template_name = "controlador/index.html"), name='leerDispositivo'),
    path('controlador/detalle/<str:pk>', DispositivoDetalle.as_view(template_name = "controlador/detalles.html"), name='detallesDispositivo'),
    path('controlador/crear', DispositivoCrear.as_view(template_name = "controlador/crear.html"), name='crearDispositivo'),
    path('controlador/editar/<str:pk>', DispositivoActualizar.as_view(template_name = "controlador/actualizar.html"), name='actualizarDispositivo'),
    path('controlador/eliminar/<str:pk>', DispositivoEliminar.as_view(), name='eliminarDispositivo'),

    path('sensor/', SensorListado.as_view(template_name = "sensor/index.html"), name='leerSensor'),
    path('sensor/detalle/<str:pk>', SensorDetalle.as_view(template_name = "sensor/detalles.html"), name='detallesSensor'),
    path('sensor/crear', SensorCrear.as_view(template_name = "sensor/crear.html"), name='crearSensor'),
    path('sensor/editar/<str:pk>', SensorActualizar.as_view(template_name = "sensor/actualizar.html"), name='actualizarSensor'),
    path('sensor/eliminar/<str:pk>', SensorEliminar.as_view(), name='eliminarSensor'),

    path('actuador/', ActuadorListado.as_view(template_name = "actuador/index.html"), name='leerActuador'),
    path('actuador/detalle/<str:pk>', ActuadorDetalle.as_view(template_name = "actuador/detalles.html"), name='detallesActuador'),
    path('actuador/crear', ActuadorCrear.as_view(template_name = "actuador/crear.html"), name='crearActuador'),
    path('actuador/editar/<str:pk>', ActuadorActualizar.as_view(template_name = "actuador/actualizar.html"), name='actualizarActuador'),
    path('actuador/eliminar/<str:pk>', ActuadorEliminar.as_view(), name='eliminarActuador'),

    path('tipo-sensor/', TipoSensorListado.as_view(template_name = "tipo-sensor/index.html"), name='leerTipoSensor'),
    path('tipo-sensor/detalle/<str:pk>', TipoSensorDetalle.as_view(template_name = "tipo-sensor/detalles.html"), name='detallesTipoSensor'),
    path('tipo-sensor/crear', TipoSensorCrear.as_view(template_name = "tipo-sensor/crear.html"), name='crearTipoSensor'),
    path('tipo-sensor/editar/<str:pk>', TipoSensorActualizar.as_view(template_name = "tipo-sensor/actualizar.html"), name='actualizarTipoSensor'),
    path('tipo-sensor/eliminar/<str:pk>', TipoSensorEliminar.as_view(), name='eliminarSensor'),

    path('tipo-actuador/', TipoActuadorListado.as_view(template_name = "tipo-actuador/index.html"), name='leerTipoActuador'),
    path('tipo-actuador/detalle/<str:pk>', TipoActuadorDetalle.as_view(template_name = "tipo-actuador/detalles.html"), name='detallesTipoActuador'),
    path('tipo-actuador/crear', TipoActuadorCrear.as_view(template_name = "tipo-actuador/crear.html"), name='crearTipoActuador'),
    path('tipo-actuador/editar/<str:pk>', TipoActuadorActualizar.as_view(template_name = "tipo-actuador/actualizar.html"), name='actualizarTipoActuador'),
    path('tipo-actuador/eliminar/<str:pk>', TipoActuadorEliminar.as_view(), name='eliminarTipoActuador'),

    path('monitor/', SensorMonitor.as_view(template_name = "sensor/monitor2.html"), name='monitorSensor'),
    path('monitor-example/', SensorMonitor2.as_view(template_name = "sensor/monitor3.html"), name='monitorSensor2'),

    path('sensor/pub/<str:id_sensor>', SensorPubListado.as_view(template_name = "pub-sensor/index.html"), name='leerSensorPub'),

    #path('plot/<int:id_sensor>', plot, name='plot'),

    #  ajax_calls
    path('ajax/controller-details/<int:pk>', ajax_controlador_detalle, name='ajax_controller_detail'),
    path('ajax/controller-edit/<int:pk>', ajax_controlador_actualizar, name='ajax_controller_edit'),
    path('ajax/sensor-pubs/<int:id_sensor>', ajax_sensor_pubs, name='ajax_sensor_pub'),
    path('ajax/status-pubs/<int:id_controller>', ajax_status_pubs, name='ajax_status_pub'),
    path('ajax/sensor-plot/<int:id_sensor>', ajax_sensor_plot, name='ajax_sensor_plot'),
    path('ajax/controller-plot/<int:id_controller>', ajax_controller_plot, name='ajax_controller_plot'),

]

persona/urls.py
# persona/urls.py
from django.urls import path
from django.contrib.auth import get_user_model
from persona.views import register, activation_sent_view, activate, activation_complete_view, \
     ObjetoDetalle, edit_user, set_timezone


urlpatterns = [

    path('signup/', register, name="signup"),
    path('sent/', activation_sent_view, name="activation_send"),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate'),
    path('activated/', activation_complete_view, name='activation_complete'),

    path('user/editar/<str:pk>', edit_user, name='actualizarUser'),
    path('user/detalle/<str:pk>', ObjetoDetalle.as_view(template_name="user/detalles.html",
                                                           model = get_user_model(),
                                                           extra_context={'titulo':'Cuenta'}
                                                           ), name='detallesUser'),
    path('user/set-timezone/', set_timezone, name='setTimezone'),
]

project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static


from .views import about, contact, inicio, tablero, set_user_timezone
# from .mqtt_to_pg import mqtt_loop
from .mqtt_to_database import mqtt_loop
from concurrent.futures import ThreadPoolExecutor

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name='inicio'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    #path('tablero/', tablero, name='tablero'),
    #path('accounts/', include('registration.backends.default.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('set-user-timezone/', set_user_timezone, name='set_user_timezone'),

    path('', include('estructura.urls')),
    path('', include('dispositivo.urls')),
    path('', include('persona.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.sites.AdminSite.site_header = 'Administración'

mqtt_loop()

dispositivo/models.py
from django.db import models
from persona.models import User
#from estructura.models import UserDispositivo

# Create your models here.
class Dispositivo(models.Model):
    nombre = models.CharField("Nombre del Controlador", max_length=30)

    class Meta:
        db_table = 'dispositivo'
        
    def __str__(self):
        return self.nombre


class TipoSensor(models.Model):
    descripcion = models.CharField(max_length=50)

    class Meta:
        db_table = 'tipo_sensor'
        
    def __str__(self):
        return self.descripcion
        
        
class Sensor(models.Model):
    id_dispositivo_fk = models.ForeignKey(Dispositivo, 
                                          models.DO_NOTHING, 
                                          db_column='id_dispositivo_fk',
                                          verbose_name="Controlador",
                                          related_name='sensor')
    tipo = models.ForeignKey('TipoSensor',
                             models.DO_NOTHING,
                             db_column='id_tipo_sensor_fk',
                             verbose_name="Tipo de Sensor")

    descripcion = models.CharField("Descripción", max_length=20)

    class Meta:
        db_table = 'sensor'
        
    def __str__(self):
        return self.descripcion
    
    
class TipoActuador(models.Model):
    descripcion = models.CharField(max_length=50)

    class Meta:
        db_table = 'tipo_actuador'
        
    def __str__(self):
        return self.descripcion


class Actuador(models.Model):
    id_dispositivo_fk = models.ForeignKey(Dispositivo, 
                                          models.DO_NOTHING, 
                                          db_column='id_dispositivo_fk',
                                          verbose_name="Controlador",
                                          related_name='actuador')
    tipo = models.ForeignKey('TipoActuador',
                             models.DO_NOTHING,
                             db_column='id_tipo_actuador_fk',
                             verbose_name="Tipo de Actuador")

    descripcion = models.CharField("Descripción", max_length=20)

    class Meta:
        db_table = 'actuador'
        
    def __str__(self):
        return self.descripcion


class PublicacionActuador(models.Model):
    id_actuador_fk = models.ForeignKey(Actuador, models.DO_NOTHING, db_column='id_actuador_fk')
    fecha = models.DateTimeField()
    valor = models.DecimalField(max_digits=3, decimal_places=0)

    class Meta:
        db_table = 'publicacion_actuador'
        
    def __str__(self):
        return str(self.id_actuador_fk) + " | " + str(self.fecha)


class PublicacionSensor(models.Model):
    id_sensor_fk = models.ForeignKey('Sensor', models.DO_NOTHING, db_column='id_sensor_fk')
    fecha = models.DateTimeField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'publicacion_sensor'
        
    def __str__(self):
        return str(self.id_sensor_fk) + " | " + str(self.fecha)

    


class PublicacionControlador(models.Model):
    controlador = models.ForeignKey('Dispositivo', models.DO_NOTHING, db_column='controlador')
    fecha = models.DateTimeField()
    valor = models.DecimalField(max_digits=1, decimal_places=0)

    class Meta:
        db_table = 'publicacion_controlador'
        
    def __str__(self):
        return str(self.controlador) + " | " + str(self.fecha)



class Logs(models.Model):
    fecha = models.DateTimeField()
    evento = models.TextField()

    class Meta:
        db_table = 'logs'
        
    def __str__(self):
        return str(self.fecha) + " | " + self.evento


        

dispositivo/forms.py
from .models import Dispositivo
from django.forms.models import ModelForm

class DispositivoForm(ModelForm):
    class Meta:
        model = Dispositivo
        fields = '__all__'

dispositivo/templates/sensor/actualizar.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

	{% block content %}
	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Sensores</h1>
	
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Editar Sensor</h6>
		</div>
		<div class="card-body">
		
			<div class='row'>
				<div class='col-sm-6 col-sm-offset-3'>		
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
					  
						{{ form|crispy }}
											
						<button type="submit" class="btn btn-primary">
							<i class="fas fa-save"></i>
							Aceptar
						</button>						
						<a href="../" type="submit" class="btn btn-primary">
							<i class="fas fa-caret-left"></i>
							Cancelar
						</a>		
					</form>
				</div>
			</div>
		</div>
	</div>
				
	{% endblock %}

dispositivo/templates/sensor/crear.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

	{% block content %}
	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Sensores</h1>
	
	
	<div class='row'>
		<div class='col-sm-8 col-sm-offset-3'>
			<div class="card shadow mb-4">
			
				<div class="card-header py-3">
					<h6 class="m-0 font-weight-bold text-primary">Nuevo Sensor</h6>
				</div>
				
				<div class="card-body">
		
					<form method="post" enctype="multipart/form-data">
						{% csrf_token %}
					  
						{{ form|crispy }} 
					  
						<button type="submit" class="btn btn-primary">
							<i class="fas fa-save"></i>
							Aceptar
						</button>
						
						<a href="./" type="submit" class="btn btn-primary">
							<i class="fas fa-caret-left"></i>
							Cancelar
						</a>
					 
					</form>
			
				</div>
			</div>
		</div>
	</div>
	{% endblock %}

dispositivo/templates/sensor/detalles.html
{% extends "base.html" %}
{% load static %}
	{% block content %}
	<!-- Page Heading -->
	<h1 class="h3 mb-2 text-gray-800">Sensores</h1>
		
	<div class="card shadow mb-4">
		<div class="card-header py-3">
			<h6 class="m-0 font-weight-bold text-primary">Detalles del Sensor</h6>
		</div>
		<div class="card-body">
		
			<div class='row'>
				<div class='col-sm-6 col-sm-offset-3'>		
					<p><strong>ID:</strong><br> {{object.id_sensor}}</p>
					<p><strong>Dispositivo:</strong><br> {{object.id_dispositivo_fk}}</p>
					<p><strong>Tipo de Sensor:</strong><br> {{object.id_tipo_sensor_fk}}</p>
					<p><strong>Descripci&oacute;n:</strong><br> {{object.descripcion}}</p>
					
					<a href="../" type="submit" class="btn btn-primary">
						<i class="fas fa-caret-left"></i>
						Volver
					</a>
					
				</div>
			</div>
		</div>
	</div>
	

	{% endblock %}

dispositivo/templates/sensor/index.html
{% extends "crud/list.html" %}

{% block table %}

<thead>
	<tr>
		<th style="width: 5%;">ID</th>
		<th>Controlador Host</th>
		<th>Tipo Sensor</th>
		<th>Descripción</th>
		<th style="width: 5%;">Acciones</th>
	</tr>
</thead>

<tbody>
	{% for object in object_list %}
	<tr>
		<td>{{ object.id }}</td>
		<td>{{ object.id_dispositivo_fk }}</td>
		<td>{{ object.tipo }}</td>
		<td>{{ object.descripcion }}</td>
		<td>
			<!-- Usaremos un formulario que realizara la tarea de eliminar un registro o postre desde la misma tabla HTML -->
			<form method="POST" action="eliminar/{{object.id}}">
				{% csrf_token %}
				<div class="btn-group">
					<!-- Creamos 3 botones que son ver, Editar y Eliminar, nos sirven para gestionar nuestros registros o postres -->
					<a href="detalle/{{object.id}}" title="Ver" class="btn btn-success">
						<i class="far fa-eye"></i></a>
					<a href="editar/{{object.id}}" title="Editar" class="btn btn-primary">
						<i class="far fa-edit"></i></a>
					<button class="btn btn-danger" onclick="return eliminar();" title="Eliminar">
						<i class="far fa-trash-alt"></i></button>
				</div>
			</form>
		</td>
	</tr>
	{% endfor %}
</tbody>

{% endblock %}

dispositivo/templates/sensor/monitor3.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}Tablero{% endblock %}


{% block in_head %}
	<script src="{% static '/mqtt/custom-mqtt.js' %}"></script>	
{% endblock %}


{% block content %}

	<div id="messages" class="alert alert-primary" role="alert"></div>

	<!-- Page Heading -->
	<div class="d-sm-flex align-items-center justify-content-between mb-4">
		<h1 class="h3 mb-0 text-gray-800">Invernadero</h1>
<!--		<a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" onclick="return cambiar_color();">
			<i class="fas fa-download fa-sm text-white-50"></i> Prueba</a>-->
	</div>

	<!-- Content Row -->
	<div class="row"> 
	
		<!-- Card Sector -->
		<div class="col-xl-12 col-lg-7">
			<div class="card shadow mb-4">
				<!-- Card Header - Dropdown -->
				<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
					<h6 class="m-0 font-weight-bold text-primary">Sector 1</h6>
					<div class="dropdown no-arrow">
						<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
						</a>
						<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
							<div class="dropdown-header">Dropdown Header:</div>
							<a class="dropdown-item" href="#">Action</a>
							<a class="dropdown-item" href="#">Another action</a>
							<div class="dropdown-divider"></div>
							<a class="dropdown-item" href="#">Something else here</a>
						</div>
					</div>
				</div>
				<!-- Card Body -->
				<div class="card-body">
				
					<!-- Titulo -->
					<h3 class="h6 mb-1 text-gray-800">Sensores</h3>
					<div class="row">			
				
						<!-- Card Temperatura -->
						<div class="col-xl-3 col-md-6 mb-4">
							<div class="card border-left-danger shadow h-100 pb-3">				
								<div class="card-body pb-0">				
									<div class="row no-gutters align-items-center pb-1">
										<div class="col mr-2">
											<div class="text-xs font-weight-bold text-danger text-uppercase mb-1">
												Temperatura</div>
											<div class="row no-gutters align-items-center">
												<div id="sensor-1" class="h5 mb-0 font-weight-bold text-gray-800">
													---</div>
												<div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
													&deg;C</div>											
											</div>
										</div>
										<div class="col-auto dropdown no-arrow">
											<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
												<i class="fas fa-temperature-low fa-2x text-gray-500"></i>
											</a>
											<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
												<a class="dropdown-item" href="#" data-toggle="modal" data-target="#exampleModalCenter">Chart</a>
												<a class="dropdown-item" href="/dispositivo/sensor/editar/1">Editar</a>
												<a class="dropdown-item" href="#">Ajustes</a>
											</div>
										</div>
									</div>
									<div class="text-xs text-gray-700">Rango permitido: 30 a 40&deg;C</div>	
								</div>
							</div>
						</div>
				
						<!-- Card Humedad -->
						<div class="col-xl-3 col-md-6 mb-4">
							<div class="card border-left-primary shadow h-100 pb-3">
								<div class="card-body  pb-0">
									<div class="row no-gutters align-items-center pb-1">
										<div class="col mr-2">
											<div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
												Humedad Interna</div>
											<div class="row no-gutters align-items-center">
												<div class="col-auto">								
													<div class="row no-gutters align-items-center">
														<div id="sensor-3" class="h5 mb-0 font-weight-bold text-gray-800">
															---</div>
														<div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
															%</div>											
													</div>
												</div>
												<div class="col">
													<div class="progress progress-sm mr-2">
														<div id="progress-3" class="progress-bar bg-primary" role="progressbar" style="width: 5%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
															</div>
													</div>
												</div>
											</div>
										</div>
										<div class="col-auto dropdown no-arrow">
											<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
												<i class="fas fa-tint fa-2x text-gray-500"></i>
											</a>
											<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
												<a class="dropdown-item" href="#">Chart</a>
												<a class="dropdown-item" href="#">Editar</a>
												<a class="dropdown-item" href="#">Ajustes</a>
											</div>
										</div>
									</div>
									<div class="text-xs text-gray-700">Rango permitido: 75 a 80%</div>
								</div>
							</div>
						</div>
						
						
				
				
				<!-- Area Chart -->
					<div class="col-xl-12 col-lg-7">
						<div class="card shadow mb-4">
							<!-- Card Header - Dropdown -->
							<div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
								<h6 class="m-0 font-weight-bold text-success">Sistema Hidrop&oacute;nico</h6>
								<div class="dropdown no-arrow">
									<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
										<i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
									</a>
									<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
										<div class="dropdown-header">Dropdown Header:</div>
										<a class="dropdown-item" href="#">Action</a>
										<a class="dropdown-item" href="#">Another action</a>
										<div class="dropdown-divider"></div>
										<a class="dropdown-item" href="#">Something else here</a>
									</div>
								</div>
							</div>
							<!-- Card Body Hidroponico -->
							<div class="card-body">
								<!-- Titulo -->
								<h3 class="h6 mb-1 text-gray-800">Controladores</h3>
								<div class="row">			
									<!-- Card Humedad -->
									<div class="col-xl-3 col-md-6 mb-4">
										<div class="card border-left-primary shadow h-100 pb-3">
											<div class="card-body  pb-0">
												<div class="row no-gutters align-items-center pb-1">
													<div class="col mr-2">
														<div class="text-sm font-weight-bold text-primary mb-1">
															Timer</div>
														<div class="row no-gutters align-items-center">
															<div class="col-auto">								
																<div class="row no-gutters align-items-center">
																	<div id="timer-1" class="h5 mb-0 mr-3 font-weight-bold text-gray-800">
																		---</div>										
																</div>
															</div>
															<div class="col">
																<div class="progress progress-sm mr-2">
																	<div id="progress-9" class="progress-bar bg-primary" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="14">
																		</div>
																</div>
															</div>
														</div>
													</div>
													<div class="col-auto dropdown no-arrow">
														<a class="dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
															<i class="fas fa-wave-square fa-2x text-gray-500"></i>
														</a>
														<div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
															<a class="dropdown-item" href="#">Chart</a>
															<a class="dropdown-item" href="#">Editar</a>
															<div class="dropdown-item" id="timer-1-ajustes" data-toggle="modal" data-target=".bd-example-modal-lg">Ajustes</div>
														</div>
													</div>
												</div>
												<div class="text-xs text-gray-700">Rango permitido: 30 a 80%</div>
											</div>
										</div>

										<template id="template">
												<div class="row">
													<div class="col-sm-12">
											
											
															<div id="div_id_descripcion" class="form-group"> 
																<label for="id_descripcion" class="control-label  requiredField">
																	Descripci&oacute;n
																	<span class="asteriskField">*</span> 
																</label> 
																<div class="controls ">
																	<input type="text" name="descripcion" maxlength="20" class="textinput textInput form-control" required id="id_descripcion">
																</div>
															</div>
													 
																		  
															<button type="submit" class="btn btn-success" data-dismiss="modal">
																<i class="fas fa-save"></i>
																Aceptar
															</button>
																			
															<button type="submit" class="btn btn-primary" data-dismiss="modal"	>
																<i class="fas fa-caret-left"></i>
																Cancelar
															</button>			
											
													</div>
												</div>
											</template>







									</div>

							
									
							
								</div>
							</div>
						</div>
					</div>	
				
				
				
			</div>
		</div>				
					
					
				
			
	</div>
	
<!-- Modal -->
<!-- <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">Chart</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				


                  <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                  </div>


			</div>
		</div>
	</div>
</div> -->

<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog modal-lg modal-dialog-centered">
		<div class="modal-content">
			<div class="modal-header">
				<h4 class="modal-title">Habitaciones Disponibles</h4>
				<button type="button" class="close" data-dismiss="modal" aria-label="close">
					<span aria-hidden="true">x</span>
				</button>
			</div>
			<div class="modal-body">
			
			</div>
		</div>
	</div>
</div>
 
	

	
		<script type="text/javascript">

			$("#timer-1-ajustes").click(function () {
				$(".modal-body div").remove();
				$(".modal-body").append($("#template").html());	
				$(".modal-title").text("Ajustes - Timer 1");
						
			});


			MQTTconnect();		
		</script>
	
{% endblock %}